---
title: "variable distribution"
author: "Xiaoting Chen"
date: "2024-02-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(ggplot2)
library(dplyr)
```

## JHS event

```{r}
incevtchd <- read.csv("/Users/cxt/Documents/research/CVD/Effect-of-nSES-on-CVD/Data/JHS/event_files/incevtchd.csv") %>%
  rename(years_chd = years, Status_chd = Status)

incevtstroke <- read.csv("/Users/cxt/Documents/research/CVD/Effect-of-nSES-on-CVD/Data/JHS/event_files/incevtstroke.csv") %>%
  rename(years_stroke = years, Status_stroke = Status)

```

```{r}

event_dat <- inner_join(incevtchd, incevtstroke, by = "subjid") %>%
  mutate(cvd_event = case_when(
    # If any of CHD, STROKE, or HARDCHD is 1
    CHD == 1 | stroke == 1 | hardCHD == 1 ~ 1,
    
    # If all of CHD, STROKE, and HARDCHD are NA
    is.na(CHD) & is.na(stroke) & is.na(hardCHD) ~ NA_integer_,
    
    # Otherwise
    TRUE ~ 0
  )) %>%
  mutate(cvd_event_t = case_when(
    cvd_event == 1 ~ pmin(years_chd, hardyears, years_stroke, na.rm = TRUE),
    TRUE ~ NA_real_  # Assign NA for cases where cvd_event != 1
  )) %>%
  filter(!is.na(cvd_event))

```

```{r}
ggplot(incevtchd[incevtchd["CHD"]==1, ], aes(x = years_chd)) +
  geom_histogram(binwidth = 1, color = "black", fill = "lightblue") +
  theme_minimal() +
  labs(title = "Frequency of Years until CHD",
       x = "Years until CHD",
       y = "Frequency")

```

```{r}
ggplot(incevtstroke[incevtstroke$stroke==1, ], aes(x = years_stroke)) +
  geom_histogram(binwidth = 1, color = "black", fill = "#FFB6C1") +
  theme_minimal() +
  labs(title = "Frequency of Years until stroke",
       x = "Years until stroke",
       y = "Frequency")
```

```{r}
sum(event_dat$cvd_event == 1, na.rm = T)

ggplot(event_dat[event_dat$cvd_event==1, ], aes(x = cvd_event_t)) +
  geom_histogram(binwidth = 1, color = "black", fill = "#90EE90") +
  theme_minimal() +
  labs(title = "Frequency of Years until any CVD",
       x = "Years until CVD",
       y = "Frequency")
```


## MESA

```{r}
mesa <- read.csv("/Users/cxt/Documents/research/CVD/Effect-of-nSES-on-CVD/Data/MESA/outcomes/event.csv") %>%
  mutate(cvd_event_hf = case_when( 
    chda == 1 | strk == 1 | mi == 1 | chf == 1 ~ 1,
    is.na(chda) & is.na(strk) & is.na(mi) & is.na(chf) ~ NA_integer_,
    TRUE ~ 0
  )) %>%
  mutate(cvd_event_hf_t = case_when(
    cvd_event_hf == 1 ~ pmin(chdatt, strktt, mitt, chftt, na.rm = TRUE),
    TRUE ~ NA_real_ 
  )) %>%
  mutate(cvd_event_nohf = case_when( 
    chda==1 | strk==1 | mi==1 | rca==1 | ang==1 | ptca==1 | cbg==1 | othrev==1 | pvd==1~ 1,
    is.na(chda) & is.na(strk) & is.na(mi) & is.na(rca) & 
      is.na(ang) & is.na(ptca) & is.na(cbg) & is.na(othrev) & is.na(pvd) ~ NA_integer_,
    TRUE ~ 0
  ))
 
sum(mesa$cvd_event_hf,na.rm = T)
sum(mesa$cvda,na.rm = T)
```

