---
title: "plots"
author: "Xiaoting Chen"
date: "2023-09-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
```


## Mediation 

### data

```{r}
setwd("../results/MESA/mediation")

# List all CSV files in the directory
files <- list.files(pattern = "\\.csv$")

# Function to read each file and add a column with the file name
read_csv_add_filename <- function(file) {
  data <- read.csv(file, stringsAsFactors = FALSE)
  data$SourceFile <- file # Add a new column with the file name
  return(data)
}

# Read each CSV file, add file name, and combine them into one data frame
mesa_mediation <- do.call(rbind, lapply(files, read_csv_add_filename)) %>%
  separate(col = SourceFile, into = c("new_col1", "nb_exposure", "ind_mediator"), sep = "_") %>%
  separate(col = ind_mediator, into = c("ind_mediator","format")) %>%
  select(-c(1,7,10)) %>%
  filter(Effect != "Prop. Mediated")

mesa_mediation$Effect <- factor(mesa_mediation$Effect, levels =unique(mesa_mediation$Effect))

```


### plotting
```{r}
plt_dat <- mesa_mediation[(mesa_mediation$nb_exposure == "nRS")&(mesa_mediation$Data == "mesa_pre"), ]

plot <- ggplot(plt_dat, aes(x = Estimate, y = ind_mediator, color = Effect)) +
            geom_point(position = position_dodge(width = 0.5), size=3.5) +  
            geom_errorbarh(aes(xmin = X95_CI_Lower, xmax = X95_CI_Upper), 
                           height = 0.2, position = position_dodge(width = 0.5), size =2) +
            labs(x = "Effect",
                 y = "Individual potential mediator") +
            geom_vline(xintercept = 0, linetype = "dashed", color = "black") +
            theme_minimal() +
            ggtitle("nRS as exposure using MESA preprocessed data") +
            theme(axis.text = element_text(size = 15),
                  axis.title = element_text(size = 15),
                  legend.text = element_text(size = 15),
                  legend.title = element_text(size = 15),
                  plot.title = element_text(size = 20))

ggsave("nRS_mesa_pre.png", plot = plot, path = "../results/mediation_plots", width = 10, height = 8, dpi = 300)
```


## Moderation

### data
```{r}
mesa_bla_moderation <- read.csv("../results/MESA_bla/moderation.csv") %>%
  separate(col = Bootstrap.Result.Name, sep = "_", 
           into = c("bootstrap", "number", "nb_exposure", "ind_moderator")) %>%
  select(-c(1,3,4))
```

#### plotting
```{r}
plt_dat <- mesa_bla_moderation[(mesa_bla_moderation$nb_exposure == "nSES"), ]

plot <- ggplot(plt_dat, aes(x = Mean, y = ind_moderator, color = Data)) +
            geom_point(position = position_dodge(width = 0.5), size=3.5) +  
            geom_errorbarh(aes(xmin = X2.5., xmax = X97.5.), 
                           height = 0.2, position = position_dodge(width = 0.5), size =2) +
            labs(x = "Estimated Coefficient of Interaction Term",
                 y = "Individual potential moderator") +
            geom_vline(xintercept = 0, linetype = "dashed", color = "black") +
            theme_minimal() +
            ggtitle("Moderation of individual features on nSES") +
            theme(axis.text = element_text(size = 15),
                  axis.title = element_text(size = 15),
                  legend.text = element_text(size = 15),
                  legend.title = element_text(size = 15),
                  plot.title = element_text(size = 20))

ggsave("mesa_bla_nSES.png", plot = plot, path = "../results/moderation_plots", width = 10, height = 8, dpi = 300)
```

